import { chromium } from '@playwright/test';
const URL='http://127.0.0.1:8854';
const b=await chromium.launch();
const c=await b.newContext({viewport:{width:1512,height:950}});
const p=await c.newPage();
const errs=[],calls=[];
p.on('pageerror',e=>errs.push('pageerror: '+e.message));
p.on('response',r=>{if(r.url().includes('/api/')){if(r.status()>=400&&!r.url().includes('/v1/me'))errs.push(r.status()+' '+r.request().method()+' '+r.url().replace(URL,'')); if(r.request().method()!=='GET')calls.push(r.request().method()+' '+r.url().replace(URL,'')+' -> '+r.status());}});
await p.goto(URL,{waitUntil:'domcontentloaded'});
await p.request.post(URL+'/api/v1/auth/demo');
await p.goto(URL+'/copilot',{waitUntil:'networkidle'}); await p.waitForTimeout(800);
await p.getByRole('button',{name:'New conversation'}).click(); await p.waitForTimeout(600);
await p.getByText('Let it prepare writes').click(); await p.waitForTimeout(300);
const ta=p.getByPlaceholder(/Ask/);
await ta.fill('Add a note to Rheinwerk Antriebstechnik saying CRITIC APPROVAL TEST 42.');
await p.keyboard.press('Enter'); await p.waitForTimeout(4000);
// inspect exact arguments
await p.getByRole('button',{name:'Show the exact arguments'}).click(); await p.waitForTimeout(400);
const t0=await p.locator('main').innerText();
console.log('EXACT ARGS:', (t0.match(/Show the exact arguments[\s\S]{0,500}/)||[''])[0].replace(/\n/g,' | '));
await p.screenshot({path:'/tmp/crit-drive/23-args.png',fullPage:true});
await p.getByRole('button',{name:'Approve and run'}).click();
await p.waitForTimeout(4000);
await p.screenshot({path:'/tmp/crit-drive/24-approved.png',fullPage:true});
const t=await p.locator('main').innerText();
console.log('\n=== AFTER APPROVE ===\n'+t.slice(t.indexOf('CRITIC APPROVAL TEST')).slice(0,1800));
console.log('\nCALLS:',calls);
console.log('ERRS',errs);
await b.close();
