import { chromium } from '@playwright/test';
const URL='http://127.0.0.1:8854';
const b=await chromium.launch();
const c=await b.newContext({viewport:{width:1512,height:950}});
const p=await c.newPage();
const errs=[];
p.on('pageerror',e=>errs.push('pageerror: '+e.message));
p.on('response',r=>{if(r.url().includes('/api/')&&r.status()>=400&&!r.url().includes('/v1/me'))errs.push(r.status()+' '+r.request().method()+' '+r.url().replace(URL,''))});
await p.goto(URL,{waitUntil:'domcontentloaded'});
await p.request.post(URL+'/api/v1/auth/demo');
const snap=async(tag)=>{
  await p.waitForTimeout(900);
  const sub=await p.locator('main').innerText();
  const head=sub.split('\n').slice(0,3).join(' || ');
  const kpi=(sub.match(/Open pipeline[\s\S]{0,400}/)||[''])[0].split('\n').filter(Boolean).slice(0,14).join(' | ');
  const cards=await p.locator('.pl-card').count();
  console.log(`\n### ${tag}\nSUBTITLE: ${head}\nKPIs: ${kpi}\ncards on board: ${cards}`);
};
await p.goto(URL+'/deals',{waitUntil:'networkidle'}); await snap('baseline');
await p.goto(URL+'/deals?owner=usr_seed05',{waitUntil:'networkidle'}); await snap('owner=usr_seed05');
await p.goto(URL+'/deals?forecast=commit',{waitUntil:'networkidle'}); await snap('forecast=commit');
await p.goto(URL+'/deals?horizon=overdue',{waitUntil:'networkidle'}); await snap('horizon=overdue');
await p.goto(URL+'/deals?closed=1',{waitUntil:'networkidle'}); await snap('closed=1');
await p.goto(URL+'/deals?pipeline=renewal',{waitUntil:'networkidle'}); await snap('pipeline=renewal');
await p.goto(URL+'/deals?q=Thornbury',{waitUntil:'networkidle'}); await snap('q=Thornbury');
await p.goto(URL+'/deals?q=zzzznomatch',{waitUntil:'networkidle'}); await snap('q=zzzznomatch');
await p.screenshot({path:'/tmp/crit-drive/12-nomatch.png'});
console.log('empty state text:',(await p.locator('main').innerText()).slice(0,1200));
console.log('ERRS',errs);
await b.close();
