import { chromium } from '@playwright/test';
const URL='http://127.0.0.1:8854';
const b=await chromium.launch();
const c=await b.newContext({viewport:{width:1512,height:950}});
const p=await c.newPage();
const errs=[];
p.on('pageerror',e=>errs.push('pageerror: '+e.message));
p.on('response',r=>{if(r.url().includes('/api/')&&r.status()>=400&&!r.url().includes('/v1/me'))errs.push(r.status()+' '+r.request().method()+' '+r.url().replace(URL,''))});
await p.goto(URL,{waitUntil:'domcontentloaded'});
await p.request.post(URL+'/api/v1/auth/demo');
await p.goto(URL+'/deals?display=table',{waitUntil:'networkidle'}); await p.waitForTimeout(900);
await p.screenshot({path:'/tmp/crit-drive/13-table.png',fullPage:false});
console.log('rows',await p.locator('table tbody tr').count());
console.log('HEAD:',(await p.locator('table thead').innerText()).replace(/\n/g,' | '));
console.log('FOOT:',(await p.locator('table tfoot').innerText().catch(()=>'no tfoot')).replace(/\n/g,' | '));
console.log('ROW1:',(await p.locator('table tbody tr').first().innerText()).replace(/\n/g,' | '));
// in-table search
const sb=p.getByPlaceholder('Filter the deals on screen');
await sb.fill('Thornbury'); await p.waitForTimeout(700);
console.log('\nafter in-table search "Thornbury": rows',await p.locator('table tbody tr').count());
console.log('FOOT:',(await p.locator('table tfoot').innerText().catch(()=>'')).replace(/\n/g,' | '));
console.log('page subtitle:',(await p.locator('main').innerText()).split('\n')[2]);
await p.screenshot({path:'/tmp/crit-drive/14-table-search.png'});
await sb.fill('');
await p.waitForTimeout(500);
// sort by amount asc
await p.locator('table thead').getByText('Amount',{exact:true}).click(); await p.waitForTimeout(500);
console.log('\nafter sort click, row1:',(await p.locator('table tbody tr').first().innerText()).replace(/\n/g,' | '));
console.log('ERRS',errs);
await b.close();
