import { chromium } from '@playwright/test';
const URL='http://127.0.0.1:8854';
const b=await chromium.launch();
const c=await b.newContext({viewport:{width:1512,height:950}});
const p=await c.newPage();
const errs=[];
p.on('console',m=>{if(m.type()==='error')errs.push('console: '+m.text())});
p.on('pageerror',e=>errs.push('pageerror: '+e.message));
p.on('response',r=>{if(r.url().includes('/api/')&&r.status()>=400)errs.push(r.status()+' '+r.request().method()+' '+r.url().replace(URL,''))});
await p.goto(URL,{waitUntil:'domcontentloaded'});
await p.request.post(URL+'/api/v1/auth/demo');
await p.goto(URL+'/deals',{waitUntil:'networkidle'});
const dlg=p.locator('[role=dialog]');
await p.getByRole('button',{name:'New deal'}).first().click();
await p.waitForTimeout(400);
await dlg.locator('input').first().fill('CRITIC — pipeline audit deal');
console.log('create enabled after name only?',await dlg.getByRole('button',{name:'Create deal'}).isEnabled());
await dlg.getByLabel('Amount').fill('12345.67');
console.log('create enabled after name+amount?',await dlg.getByRole('button',{name:'Create deal'}).isEnabled());
const acct=dlg.getByLabel('Account');
await acct.fill('Thornbury');
await p.waitForTimeout(800);
await p.screenshot({path:'/tmp/crit-drive/03-acct.png'});
const listbox = p.locator('[role=listbox], [role=option]');
console.log('listbox count',await listbox.count());
if(await listbox.count()) console.log('SUGGEST:',(await listbox.first().innerText()).slice(0,300));
await p.keyboard.press('ArrowDown'); await p.waitForTimeout(200); await p.keyboard.press('Enter'); await p.waitForTimeout(400);
console.log('acct value now:',await acct.inputValue());
// date
await dlg.getByRole('button',{name:/Pick a date/}).click().catch(e=>console.log('no date btn',e.message.slice(0,80)));
await p.waitForTimeout(500);
await p.screenshot({path:'/tmp/crit-drive/04-date.png'});
const all=await p.locator('[role=dialog]').count();
console.log('dialogs',all);
console.log('DIALOG NOW:',(await dlg.innerText()).slice(0,1400));
console.log('ERRS',errs);
await b.close();
