import { chromium } from '@playwright/test';
const URL='http://127.0.0.1:8854';
const b=await chromium.launch();
const c=await b.newContext({viewport:{width:1512,height:950}});
const p=await c.newPage();
const errs=[];
p.on('console',m=>{if(m.type()==='error')errs.push('console: '+m.text())});
p.on('pageerror',e=>errs.push('pageerror: '+e.message));
p.on('response',r=>{if(r.url().includes('/api/')&&r.status()>=400)errs.push(r.status()+' '+r.request().method()+' '+r.url().replace(URL,''))});
await p.goto(URL,{waitUntil:'domcontentloaded'});
await p.request.post(URL+'/api/v1/auth/demo');
await p.goto(URL+'/deals',{waitUntil:'networkidle'});
const dlg=p.locator('[role=dialog]');
await p.getByRole('button',{name:'New deal'}).first().click();
await p.waitForTimeout(400);
await dlg.locator('input').first().fill('CRITIC — pipeline audit deal');
const amt=dlg.getByLabel('Amount');
await amt.click();
await amt.pressSequentially('12345.67',{delay:40});
await p.waitForTimeout(300);
console.log('amount input value:',await amt.inputValue());
console.log('create enabled?',await dlg.getByRole('button',{name:'Create deal'}).isEnabled());
// date picker
const date=dlg.getByLabel('Close date');
console.log('date el count',await date.count(),'tag',await date.first().evaluate(e=>e.tagName+' '+e.className));
await date.first().click();
await p.waitForTimeout(500);
await p.screenshot({path:'/tmp/crit-drive/04-date.png'});
const body=await p.locator('body').innerText();
console.log('has calendar grid?', body.includes('Mo')||body.includes('Mon')||/September|October/.test(body));
console.log('ERRS',errs);
await b.close();
