import { chromium } from '@playwright/test';
const URL='http://127.0.0.1:8854';
const b=await chromium.launch();
const c=await b.newContext({viewport:{width:1512,height:950}});
const p=await c.newPage();
await p.goto(URL,{waitUntil:'domcontentloaded'});
await p.request.post(URL+'/api/v1/auth/demo');
await p.goto(URL+'/deals',{waitUntil:'networkidle'});
const dlg=p.locator('[role=dialog]');
await p.getByRole('button',{name:'New deal'}).first().click();
await p.waitForTimeout(400);
await dlg.locator('input').first().fill('CRITIC — pipeline audit deal');
const amt=dlg.getByLabel('Amount');
await amt.click(); await amt.pressSequentially('12345.67',{delay:40});
const btn=dlg.getByRole('button',{name:'Create deal'});
console.log('before blur: enabled',await btn.isEnabled());
await amt.press('Tab'); await p.waitForTimeout(300);
console.log('after Tab:  enabled',await btn.isEnabled(),'value',await amt.inputValue());
// Now the real-user path: click Create directly after typing (fresh)
await dlg.getByRole('button',{name:'Cancel'}).click(); await p.waitForTimeout(300);
await p.getByRole('button',{name:'New deal'}).first().click(); await p.waitForTimeout(400);
await dlg.locator('input').first().fill('CRITIC — direct click test');
const amt2=dlg.getByLabel('Amount'); await amt2.click(); await amt2.pressSequentially('50000',{delay:40});
const btn2=dlg.getByRole('button',{name:'Create deal'});
console.log('typed 50000, btn enabled immediately?',await btn2.isEnabled());
await btn2.click({force:true}).catch(e=>console.log('click failed:',e.message.slice(0,60)));
await p.waitForTimeout(1200);
console.log('dialog still open after 1 click?',await dlg.isVisible().catch(()=>false));
console.log('url',p.url());
await p.screenshot({path:'/tmp/crit-drive/05-directclick.png'});
await b.close();
