import { chromium } from '@playwright/test';
const URL='http://127.0.0.1:8854';
const b=await chromium.launch();
const c=await b.newContext({viewport:{width:1512,height:950}});
const p=await c.newPage();
await p.goto(URL,{waitUntil:'domcontentloaded'});
await p.request.post(URL+'/api/v1/auth/demo');
await p.goto(URL+'/deals',{waitUntil:'networkidle'});
const dlg=p.locator('[role=dialog]');
await p.getByRole('button',{name:'New deal'}).first().click(); await p.waitForTimeout(400);
await dlg.locator('input').first().fill('CRITIC — unforced click');
const amt=dlg.getByLabel('Amount'); await amt.click(); await amt.pressSequentially('7777',{delay:40});
const btn=dlg.getByRole('button',{name:'Create deal'});
// simulate a real mouse press: move, down, up over the button
const box=await btn.boundingBox();
await p.mouse.move(box.x+box.width/2, box.y+box.height/2);
await p.mouse.down(); await p.waitForTimeout(60); await p.mouse.up();
await p.waitForTimeout(1500);
console.log('after one real mouse press — dialog open?',await dlg.isVisible().catch(()=>false),'url',p.url());
await p.screenshot({path:'/tmp/crit-drive/06-unforced.png'});
await b.close();
