import { chromium } from '@playwright/test';
const URL='http://127.0.0.1:8854';
const b=await chromium.launch();
const c=await b.newContext({viewport:{width:1512,height:950}});
const p=await c.newPage();
const errs=[];
p.on('pageerror',e=>errs.push('pageerror: '+e.message));
p.on('response',r=>{if(r.url().includes('/api/')&&r.status()>=400&&!r.url().includes('/v1/me'))errs.push(r.status()+' '+r.request().method()+' '+r.url().replace(URL,''))});
await p.goto(URL,{waitUntil:'domcontentloaded'});
await p.request.post(URL+'/api/v1/auth/demo');
await p.goto(URL+'/deals/deal_bCBbAn9Cdg2y5A',{waitUntil:'networkidle'}); await p.waitForTimeout(700);
const dlg=p.locator('[role=dialog]');
await p.getByRole('button',{name:/Closed won/}).first().click(); await p.waitForTimeout(600);
// try Mark won without picking a reason
const mw=dlg.getByRole('button',{name:'Mark won'});
console.log('Mark won enabled with no reason?',await mw.isEnabled());
await dlg.locator('select').last().selectOption({label:'Lost to competitor'});
await p.waitForTimeout(300);
console.log('Mark won enabled after picking LOST-TO-COMPETITOR on a WON deal?',await mw.isEnabled());
await dlg.locator('select').last().selectOption({label:'Product fit'});
await p.waitForTimeout(200);
await mw.click(); await p.waitForTimeout(1800);
await p.screenshot({path:'/tmp/crit-drive/11-won.png',fullPage:true});
const main=await p.locator('main').innerText();
console.log('\nAFTER WIN — header:', main.split('\n').slice(0,10).join(' | '));
console.log('has Closed won?',main.includes('Closed won'),'| Status Won?',/Status\s*Won/.test(main));
console.log('CLOSED ON section:', (main.match(/Closed on[\s\S]{0,60}/)||[''])[0].replace(/\n/g,' '));
console.log('DAYS TO CLOSE:', (main.match(/Days to close[\s\S]{0,40}/)||[''])[0].replace(/\n/g,' '));
console.log('TIMELINE:', (main.match(/Timeline[\s\S]{0,400}/)||[''])[0].replace(/\n/g,' | '));
console.log('ERRS',errs);
await b.close();
