import { chromium } from '@playwright/test';
const URL='http://127.0.0.1:8854';
const b=await chromium.launch();
const c=await b.newContext({viewport:{width:1512,height:950}});
const p=await c.newPage();
const errs=[]; p.on('pageerror',e=>errs.push('pageerror: '+e.message));
await p.goto(URL,{waitUntil:'domcontentloaded'}); await p.request.post(URL+'/api/v1/auth/demo');
await p.goto(URL+'/deals/deal_bCBbAn9Cdg2y5A',{waitUntil:'networkidle'}); await p.waitForTimeout(900);
const dlg=p.locator('[role=dialog]');
await p.getByRole('button',{name:'Log activity'}).first().click(); await p.waitForTimeout(600);
await dlg.getByRole('button',{name:'Call'}).click().catch(()=>{});
await dlg.locator('input').first().fill('CRITIC logged call');
await dlg.locator('textarea').first().fill('Spoke with the buyer about phase 2.');
await p.waitForTimeout(200);
const btn=dlg.getByRole('button',{name:/^Log /});
console.log('submit button label:',await btn.innerText());
await btn.click(); await p.waitForTimeout(1800);
await p.screenshot({path:'/tmp/crit-drive/38-logged.png',fullPage:true});
let t=await p.locator('main').innerText();
console.log('timeline has it?',t.includes('CRITIC logged call'));
await p.reload({waitUntil:'networkidle'}); await p.waitForTimeout(900);
t=await p.locator('main').innerText();
console.log('AFTER RELOAD timeline has it?',t.includes('CRITIC logged call'));
console.log('TIMELINE:',(t.match(/Timeline[\s\S]{0,300}/)||[''])[0].replace(/\n/g,' | '));
// Move stage button
await p.getByRole('button',{name:'Move stage'}).click(); await p.waitForTimeout(700);
await p.screenshot({path:'/tmp/crit-drive/39-movestage.png'});
console.log('\nMOVE STAGE MENU:',(await p.locator('[role=menu]').innerText().catch(()=>'no menu')).replace(/\n/g,' | ').slice(0,500));
console.log('ERRS',errs);
await b.close();
