import { ws } from './lib';
const log = (...a: any[]) => console.log(...a);
const w = await ws();
const cus = await w.ok('POST', '/v1/customers', { name: 'Attack One', email: 'a1@x.example', currency: 'usd' });
const sub = await w.ok('POST', '/v1/subscriptions', { customer: cus.id, items: [{ price: 'growth_monthly' }] });
await w.app.tick();
const invs = await w.ok('GET', `/v1/invoices?subscription=${sub.id}&limit=100`);
const inv = invs.data[0];
log('invoice', inv.id, inv.status, 'total', inv.total, 'due', inv.amount_due);
const pm = await w.ok('POST', '/v1/payment_methods', { type: 'card', customer: cus.id, brand: 'visa', exp_month: 4, exp_year: 2031, simulated_behavior: 'succeeds' });
const mk = () => w.ok('POST', '/v1/payment_intents', { customer: cus.id, invoice: inv.id, payment_method: pm.id });
const A = await mk(); const B = await mk();
log('A', A.id, A.amount, A.status, '| B', B.id, B.amount, B.status);
const cA = await w.call('POST', `/v1/payment_intents/${A.id}/confirm`, {});
log('confirm A ->', cA.status, cA.body.status, cA.body.amount);
const cB = await w.call('POST', `/v1/payment_intents/${B.id}/confirm`, {});
log('confirm B ->', cB.status, JSON.stringify(cB.body.error ?? { status: cB.body.status, amount: cB.body.amount }));
const after = await w.ok('GET', `/v1/invoices/${inv.id}`);
log('invoice after:', after.status, 'due', after.amount_due, 'paid', after.amount_paid, 'total', after.total);
const pays = await w.ok('GET', `/v1/invoices/${inv.id}/payments`);
log('payments view overpaid:', pays.amount_overpaid, 'charges:', JSON.stringify(pays.charges?.map((c: any) => [c.status, c.amount])));
const bal = await w.ok('GET', `/v1/customers/${cus.id}`);
log('customer balance:', bal.balance);
const charges = await w.ok('GET', `/v1/charges?customer=${cus.id}&limit=100`);
const charged = charges.data.filter((c: any) => c.status === 'succeeded').reduce((s: number, c: any) => s + c.amount, 0);
log('charged', charged, 'paid', after.amount_paid, 'credit', -bal.balance, 'RECONCILES', charged === after.amount_paid + (-bal.balance));

// ---- credit note race: new invoice, intent created, then credit note halves it
log('\n--- credit note race ---');
const cus2 = await w.ok('POST', '/v1/customers', { name: 'Attack Two', email: 'a2@x.example', currency: 'usd' });
const sub2 = await w.ok('POST', '/v1/subscriptions', { customer: cus2.id, items: [{ price: 'growth_monthly' }] });
await w.app.tick();
const inv2 = (await w.ok('GET', `/v1/invoices?subscription=${sub2.id}&limit=100`)).data[0];
const pm2 = await w.ok('POST', '/v1/payment_methods', { type: 'card', customer: cus2.id, brand: 'visa', exp_month: 4, exp_year: 2031, simulated_behavior: 'succeeds' });
const C = await w.ok('POST', '/v1/payment_intents', { customer: cus2.id, invoice: inv2.id, payment_method: pm2.id });
log('intent C amount', C.amount, 'invoice total', inv2.total);
const cn = await w.call('POST', '/v1/credit_notes', { invoice: inv2.id, lines: [{ type: 'custom_line_item', description: 'goodwill', amount: Math.floor(inv2.amount_due / 2) }] });
log('credit note ->', cn.status, cn.body.error?.code ?? cn.body.total);
const inv2b = await w.ok('GET', `/v1/invoices/${inv2.id}`);
log('invoice2 now due', inv2b.amount_due, 'total', inv2b.total);
const cC = await w.call('POST', `/v1/payment_intents/${C.id}/confirm`, {});
log('confirm C ->', cC.status, JSON.stringify(cC.body.error ?? { status: cC.body.status, amount: cC.body.amount }));
const inv2c = await w.ok('GET', `/v1/invoices/${inv2.id}`);
log('invoice2 after:', inv2c.status, 'due', inv2c.amount_due, 'paid', inv2c.amount_paid);
const bal2 = await w.ok('GET', `/v1/customers/${cus2.id}`);
log('balance2', bal2.balance);
const ch2 = await w.ok('GET', `/v1/charges?customer=${cus2.id}&limit=100`);
log('charges2', JSON.stringify(ch2.data.map((c: any) => [c.status, c.amount])));
w.close();
