import { ws } from './lib';
const log = (...a: any[]) => console.log(...a);
const DAY = 86400000;
const w = await ws();
const cus = await w.ok('POST', '/v1/customers', { name: 'Refund Overpay', email: 'ro@x.example', currency: 'usd' });
const pm = await w.ok('POST', '/v1/payment_methods', { type: 'bank_debit', customer: cus.id, bank_name: 'B', account_type: 'checking', simulated_behavior: 'succeeds' });
const sub = await w.ok('POST', '/v1/subscriptions', { customer: cus.id, items: [{ price: 'growth_monthly' }] });
await w.app.tick();
const inv = (await w.ok('GET', `/v1/invoices?subscription=${sub.id}&limit=10`)).data[0];
log('invoice due', inv.amount_due);
await w.ok('POST', '/v1/credit_notes', { invoice: inv.id, amount: 30000, reason: 'order_change' });
await w.app.travel(6 * DAY);
let i = await w.ok('GET', `/v1/invoices/${inv.id}`);
let c = await w.ok('GET', `/v1/customers/${cus.id}`);
const ch = (await w.ok('GET', `/v1/charges?customer=${cus.id}&limit=10`)).data[0];
log('state: charge', ch.amount, 'invoice paid', i.amount_paid, 'due', i.amount_due, 'balance', c.balance);
// full refund of the charge
const r = await w.call('POST', '/v1/refunds', { charge: ch.id });
log('full refund ->', r.status, r.body.error?.code ?? r.body.amount);
i = await w.ok('GET', `/v1/invoices/${inv.id}`);
c = await w.ok('GET', `/v1/customers/${cus.id}`);
const bts = (await w.ok('GET', `/v1/customers/${cus.id}/balance_transactions`)).data;
const ch2 = await w.ok('GET', `/v1/charges/${ch.id}`);
log('after refund: invoice status', i.status, 'paid', i.amount_paid, 'due', i.amount_due, 'pre_cn', i.pre_payment_credit_notes_amount, 'total', i.total);
log('charge refunded', ch2.amount_refunded, '| customer balance', c.balance);
log('balance txns', JSON.stringify(bts.map((t: any) => [t.type, t.amount, t.ending_balance])));
log('overpaid now', (await w.ok('GET', `/v1/invoices/${inv.id}/payments`)).amount_overpaid);
const netCash = ch2.amount - ch2.amount_refunded;
log(`CASH CHECK: net cash received ${netCash}; invoice paid ${i.amount_paid}; credit owed to customer ${-c.balance}; business position ${netCash - i.amount_paid - (-c.balance)} (should be 0)`);
w.close();
