import { createApp, frozenClock } from '../src/server/app';
import type { Auth } from '../src/server/kernel/http';
const ORG='org_demo';
const DANA: Auth = { kind:'session', orgId:ORG, userId:'usr_seed01', role:'owner', scopes:['*'], livemode:true };
const app = await createApp({ db:'memory', config:{env:'test'}, clock: frozenClock(Date.UTC(2026,5,1)) });
const call=(m:string,p:string,b?:unknown)=>app.handle({method:m,path:p,body:b,auth:DANA});
const ok=async(m:string,p:string,b?:unknown)=>{const r=await call(m,p,b); if(r.status>=400) throw new Error(`${m} ${p} ${r.status} ${JSON.stringify(r.body)}`); return r.body;};
const cus = await ok('POST','/v1/customers',{name:'Item4',email:'i4@x.example',currency:'usd'});
const sub = await ok('POST','/v1/subscriptions',{customer:cus.id, items:[{price:'growth_monthly'}], collection_method:'send_invoice'});
await app.tick();
const inv = (await ok('GET',`/v1/invoices?subscription=${sub.id}&limit=10`)).data[0];
console.log('invoice', inv.number, inv.status, 'total', inv.total, 'due', inv.amount_due, 'paid', inv.amount_paid);
const card = await ok('POST','/v1/payment_methods',{type:'card',customer:cus.id,brand:'visa',exp_month:4,exp_year:2031,simulated_behavior:'succeeds'});
await ok('POST','/v1/payment_intents',{customer:cus.id,invoice:inv.id,payment_method:card.id,amount:20000,confirm:true,off_session:true});
let after = await ok('GET',`/v1/invoices/${inv.id}`);
console.log('after part-pay:', after.status,'paid',after.amount_paid,'due',after.amount_due);
const r = await call('POST','/v1/credit_notes',{invoice:inv.id,amount:49900,reason:'order_change'});
console.log('credit note ->', r.status, r.status>=400? JSON.stringify(r.body):'ok');
after = await ok('GET',`/v1/invoices/${inv.id}`);
console.log('after credit note:', after.status,'paid',after.amount_paid,'due',after.amount_due,'preCredit',after.pre_payment_credit_notes_amount);
console.log('customer balance', (await ok('GET',`/v1/customers/${cus.id}`)).balance);
app.close();
